development:
  adapter: sqlite3
  database: db/development.db

#test:
#  adapter: sqlite3
#  database: db/test.db

#production:
#  adapter: postgresql
#  host: [herokuの情報]
#  port: [herokuの情報]
#  database: [herokuの情報]
#  username: [herokuの情報]
#  password: [herokuの情報]